
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = app_client
SERVER = app_server

SOURCES_CLNT.cpp = 
SOURCES_CLNT.h = 
SOURCES_SVC.cpp = 
SOURCES_SVC.h = 
SOURCES.x = app.x

TARGETS_SVC.cpp = app_svc.cpp app_server.cpp app_xdr.cpp 
TARGETS_CLNT.cpp = app_clnt.cpp app_client.cpp app_xdr.cpp 
TARGETS = app.h app_xdr.cpp app_clnt.cpp app_svc.cpp app_client.cpp app_server.cpp

OBJECTS_CLNT = $(SOURCES_CLNT.cpp:%.cpp=%.o) $(TARGETS_CLNT.cpp:%.cpp=%.o)
OBJECTS_SVC = $(SOURCES_SVC.cpp:%.cpp=%.o) $(TARGETS_SVC.cpp:%.cpp=%.o)
# Compiler flags 

CXX = g++
CXXFLAGS += -g -I/usr/include/tirpc
LDLIBS += -lnsl -ltirpc
RPCGENFLAGS = 

# Targets 

all : $(CLIENT) $(SERVER)

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.cpp) $(SOURCES_CLNT.h) $(TARGETS_CLNT.cpp) 

$(OBJECTS_SVC) : $(SOURCES_SVC.cpp) $(SOURCES_SVC.h) $(TARGETS_SVC.cpp) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.cpp) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(LINK.cpp) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

 clean:
	 $(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER)

